In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1LGIqg-K8-oefXU2OzT0Pi_vXXV7VmYN5')

## Name : Sudhakar Anemu (sudhakar.anemu@gmail.com)
### Assignment Two

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: <br>https://numpy.org/doc/stable/reference/routines.html <br>https://numpy.org/doc/stable/reference/index.html
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: **TODO - INSERT SUBMISSION LINK**
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.append
function2 = ???
function3 = ???
function4 = ???
function5 = ???

## Function 1 - np.append

Append array to the end of the Array. 
<br> Syntex : append(arr, values, axis=None)

In [37]:
arr2by3 = np.array([[1,2,3], [4,5,6]])
print("Array : arr2by3 : \n", arr2by3)

arr1by3 = np.array([[7,8,9]])
print("Array : arr1by3 : \n", arr1by3)

print("Appending both arrays  : \n", np.append(arr2by3, arr1by3))

Array : arr2by3 : 
 [[1 2 3]
 [4 5 6]]
Array : arr1by3 : 
 [[7 8 9]]
Appending both arrays  : 
 [1 2 3 4 5 6 7 8 9]


Here we verified the append function with a 2*3 and 1*3 matrix with out mentioning the axis. Then it returns the 1*9 Matrix

In [38]:
print("Appending both arrays  : \n", np.append(arr2by3, arr1by3, axis = 0))

Appending both arrays  : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Here we verified the append function with a 2 * 3 and 1 * 3 matrix with mentioning the axis=0. Then it returns the 3 * 3 matrix.

In [39]:
print("Appending both arrays  : \n", np.append(arr2by3, arr1by3, axis = 1))

ValueError: ignored

Here we tried with the axix=1, It returns an error since the mismatch of the dimentions.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'